# Generated by Django 6.0 on 2026-02-25 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_time_ativo'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_random', models.BooleanField(default=False)),
                ('battle_type', models.CharField(choices=[('trainer', 'Batalha contra Treinador'), ('bot', 'Batalha contra NPC')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Em Andamento'), ('completed', 'Concluída'), ('cancelled', 'Interrompida')], default='active', max_length=20)),
                ('winner_id', models.PositiveIntegerField(blank=True, null=True)),
                ('winner_side', models.CharField(blank=True, choices=[('player', 'Jogador'), ('opponent', 'Oponente')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('turns_count', models.PositiveIntegerField(default=0)),
                ('is_ranked', models.BooleanField(default=False)),
                ('opponent_npc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_npc', to='app.npc')),
                ('opponent_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent_battles', to='app.time')),
                ('opponent_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_opponent', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_player', to=settings.AUTH_USER_MODEL)),
                ('player_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_battles', to='app.time')),
                ('winner_content_type', models.ForeignKey(blank=True, limit_choices_to={'model__in': ('user', 'npc')}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='BattlePokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('player', 'Jogador'), ('opponent', 'Oponente')], max_length=10)),
                ('position', models.PositiveSmallIntegerField()),
                ('current_hp', models.PositiveIntegerField()),
                ('max_hp', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_fainted', models.BooleanField(default=False)),
                ('is_confused', models.BooleanField(default=False)),
                ('status_condition', models.CharField(choices=[('none', 'Nenhum'), ('paralyzed', 'Paralisado'), ('poisoned', 'Envenenado'), ('badly_poisoned', 'Gravemente Envenenado'), ('burned', 'Queimado'), ('frozen', 'Congelado'), ('asleep', 'Dormindo')], default='none', max_length=20)),
                ('attack_stage', models.SmallIntegerField(default=0)),
                ('defense_stage', models.SmallIntegerField(default=0)),
                ('special_attack_stage', models.SmallIntegerField(default=0)),
                ('special_defense_stage', models.SmallIntegerField(default=0)),
                ('speed_stage', models.SmallIntegerField(default=0)),
                ('accuracy_stage', models.SmallIntegerField(default=0)),
                ('evasion_stage', models.SmallIntegerField(default=0)),
                ('move_1_pp', models.PositiveSmallIntegerField(default=0)),
                ('move_2_pp', models.PositiveSmallIntegerField(default=0)),
                ('move_3_pp', models.PositiveSmallIntegerField(default=0)),
                ('move_4_pp', models.PositiveSmallIntegerField(default=0)),
                ('confusion_turns', models.PositiveSmallIntegerField(default=0)),
                ('sleep_turns', models.PositiveSmallIntegerField(default=0)),
                ('toxic_counter', models.PositiveSmallIntegerField(default=0)),
                ('is_protected', models.BooleanField(default=False)),
                ('is_switching', models.BooleanField(default=False)),
                ('last_move_used', models.PositiveIntegerField(blank=True, null=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_pokemons', to='batalha.battle')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pokemon')),
            ],
            options={
                'ordering': ['side', 'position'],
                'unique_together': {('battle', 'side', 'position')},
            },
        ),
        migrations.CreateModel(
            name='BattleQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Esperando'), ('matched', 'Encontrado'), ('cancelled', 'Cancelado')], default='waiting', max_length=10)),
                ('min_rating', models.PositiveIntegerField(default=0)),
                ('max_rating', models.PositiveIntegerField(default=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('player_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.time')),
            ],
        ),
        migrations.CreateModel(
            name='BattleTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveIntegerField()),
                ('player_action', models.CharField(choices=[('move', 'Usar Movimento'), ('switch', 'Trocar Pokémon')], max_length=20)),
                ('player_move_id', models.PositiveIntegerField(blank=True, null=True)),
                ('player_target', models.CharField(blank=True, max_length=10, null=True)),
                ('opponent_action', models.CharField(blank=True, max_length=20, null=True)),
                ('opponent_move_id', models.PositiveIntegerField(blank=True, null=True)),
                ('damage_dealt', models.PositiveIntegerField(default=0)),
                ('damage_taken', models.PositiveIntegerField(default=0)),
                ('status_applied', models.CharField(blank=True, max_length=20, null=True)),
                ('stat_changes', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution_order', models.JSONField(default=list)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='batalha.battle')),
                ('player_switch_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turns_switched_in', to='batalha.battlepokemon')),
            ],
        ),
        migrations.CreateModel(
            name='BattleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('damage', 'Dano'), ('status', 'Status'), ('switch', 'Troca'), ('victory', 'Vitória'), ('defeat', 'Derrota')], max_length=10)),
                ('message', models.TextField()),
                ('move_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='batalha.battle')),
                ('pokemon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='batalha.battlepokemon')),
                ('turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='batalha.battleturn')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
