# Generated by Django 6.0 on 2025-12-30 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokeapi_id', models.PositiveIntegerField()),
                ('random', models.BooleanField(default=False)),
                ('apelido', models.CharField(blank=True, max_length=50)),
                ('level', models.PositiveSmallIntegerField(default=100)),
                ('shiny', models.BooleanField(default=False)),
                ('genero', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('genderless', 'Genderless')], default='male', max_length=10)),
                ('move_1', models.PositiveIntegerField(blank=True, null=True)),
                ('move_2', models.PositiveIntegerField(blank=True, null=True)),
                ('move_3', models.PositiveIntegerField(blank=True, null=True)),
                ('move_4', models.PositiveIntegerField(blank=True, null=True)),
                ('nature', models.CharField(choices=[('hardy', 'Hardy'), ('lonely', 'Lonely'), ('brave', 'Brave'), ('adamant', 'Adamant'), ('naughty', 'Naughty'), ('bold', 'Bold'), ('docile', 'Docile'), ('relaxed', 'Relaxed'), ('impish', 'Impish'), ('lax', 'Lax'), ('timid', 'Timid'), ('hasty', 'Hasty'), ('serious', 'Serious'), ('jolly', 'Jolly'), ('naive', 'Naive'), ('modest', 'Modest'), ('mild', 'Mild'), ('quiet', 'Quiet'), ('bashful', 'Bashful'), ('rash', 'Rash'), ('calm', 'Calm'), ('gentle', 'Gentle'), ('sassy', 'Sassy'), ('careful', 'Careful'), ('quirky', 'Quirky')], default='hardy', max_length=20)),
                ('item_id', models.PositiveIntegerField(blank=True, null=True)),
                ('iv_hp', models.PositiveSmallIntegerField(default=31)),
                ('iv_atk', models.PositiveSmallIntegerField(default=31)),
                ('iv_def', models.PositiveSmallIntegerField(default=31)),
                ('iv_spa', models.PositiveSmallIntegerField(default=31)),
                ('iv_spd', models.PositiveSmallIntegerField(default=31)),
                ('iv_spe', models.PositiveSmallIntegerField(default=31)),
                ('ev_hp', models.PositiveSmallIntegerField(default=0)),
                ('ev_atk', models.PositiveSmallIntegerField(default=0)),
                ('ev_def', models.PositiveSmallIntegerField(default=0)),
                ('ev_spa', models.PositiveSmallIntegerField(default=0)),
                ('ev_spd', models.PositiveSmallIntegerField(default=0)),
                ('ev_spe', models.PositiveSmallIntegerField(default=0)),
                ('dono_npc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.npc')),
                ('dono_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='Time Indefinido', max_length=50, null=True)),
                ('dono_npc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.npc')),
                ('dono_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimePokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField()),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pokemon')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.time')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('time', 'pokemon'), name='unique_pokemon_per_time'), models.UniqueConstraint(fields=('time', 'slot'), name='unique_slot_per_time')],
            },
        ),
    ]
